### ISSUE TITLE
windows incompatible

### ISSUE THREAD

**Issue by kubinka0505** [DarkTrick/python-video-silence-cutter#7]
```py
  File "C:\Users\Jakub\python-video-silence-cutter\silence_cutter.py", line 26, in findSilences
    for i in range (len(words)):
                            ^^^^^
ValueError: could not convert string to float: '-2.08333e-05\\r'
```
cba

**Comment by DarkTrick** [comment]
Thank you very much for reporting!
Can you possibly provide a video file?

I will need a while to fix this, as I'm too busy at the moment.

**Comment by sbayrakli** [comment]
do not leave blank optional parameters when starting...

**Comment by DarkTrick** [comment]
@kubinka0505 

Can you please check if the script in branch *fix/windows_cutting*  will fix your problem?
You can get the file via `git clone -b fix/windows_cutting https://github.com/DarkTrick/python-video-silence-cutter.git`


Otherwise: 
I'd like to analyze the problem. Could you please do the following:

1. Open `silence_cutter.py`, search for `log_level = logging.ERROR` and set it to `log_level = logging.DEBUG`.
2. Run the script on the video file inside testdata: `python3 silence_cutter.py ./testdata/simple_video.mkv`. In case the error does not occur with this file, could you use the file you had the error with?
3. Please share the `silence_cutter.log` file, that will be created

**Comment by DarkTrick** [comment]
possibly related: https://github.com/DarkTrick/python-video-silence-cutter/issues/6
